### ISSUE TITLE
Confusing tag release dates

### ISSUE THREAD

**Issue by holtkamp** [zendframework/zend-i18n-resources#32]
Version 2.5.2 seems to be the latest in terms of semantic versioning, but why are the release dates for 2.4.x more "recent"?
![screen shot 2017-10-23 at 22 30 38](https://user-images.githubusercontent.com/776405/31911891-680fce08-b842-11e7-919d-d26b6a16d298.png)

https://github.com/zendframework/zend-i18n-resources/releases

**Comment by Xerkus** [comment]
Sorry for the slightly :man_facepalming: late reply.

It is because they were released after 2.5.2 and there was nothing to forward port to 2.5.*
you might notice they all share the same tree-ish id `f970e93`. It is because 2.4.* was the last framework wide release before split to independently versioned packages.
